### ISSUE TITLE
Quick View

### ISSUE THREAD

**Issue by jonathanmwood** [alike03/SubscriptionInfo#12]
Hi there, love the extension. So helpful!

Would it be possible to add the tag to games in a list view? I've attached a mockupo so you can see what I mean.

![Quick View Mockup](https://user-images.githubusercontent.com/74330965/143423817-7e761554-9820-4307-b47d-b6065e5e63f9.png)

**Comment by alike03** [comment]
There is actually Sub Display in Wishlist. You can try it by adding some Game Pass games.

![Steam Wishlist](https://user-images.githubusercontent.com/8145921/143498271-9db7ec27-bd2b-476e-8db2-ed291746216c.png)

**Comment by jonathanmwood** [comment]
Oh, I’m an idiot. Don’t know how I missed that! Thanks!From: alike03Sent: 25 November 2021 20:45To: alike03/SubscriptionInfoCc: jonathanmwood; AuthorSubject: Re: [alike03/SubscriptionInfo] Quick View (Issue #12) There is actually Sub Display in Wishlist. You can try it by adding some Game Pass games.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
