### ISSUE TITLE
Lost Words: Beyond the Page not showing as part of Game Pass even though it is

### ISSUE THREAD

**Issue by miguedevel** [alike03/SubscriptionInfo#15]
Here's the Steam url for the game: https://store.steampowered.com/app/599610/Lost_Words_Beyond_the_Page/
Here's the Xbox url for it: https://www.xbox.com/en-us/games/store/Lost-Words-Beyond-the-Page/9NN16ML9S93V

It's on both Xbox and PC Game Pass services.

**Comment by alike03** [comment]
Whoops, looks like the algorithm caught the Soundtrack Steam ID (1327700) instead of the Game Steam ID (599610).
Thanks, corrected it.
