### ISSUE TITLE
Aragami 1 is not on Game Pass nor EA Play

### ISSUE THREAD

**Issue by miguedevel** [alike03/SubscriptionInfo#21]
The listing at: https://store.steampowered.com/app/280160/Aragami/ 
shows it's on PC Gam Pass, EA Play and EA Play Pro, but the game is on neither of these services. As far as I can see, it's on Xbox Games with Gold.

**Comment by alike03** [comment]
Games on EA Play are automatically on EA Play Pro and on PC Game Pass. 
Correct. The game got removed from EA Play. EA Play is a manually maintained list. I corrected that mistake.
Thanks.
