### ISSUE TITLE
Not implemented in newer Steam store pages

### ISSUE THREAD

**Issue by nategasm** [alike03/SubscriptionInfo#25]
Subscription info is currently missing from Steam's newer store pages like categories/tags/genres

Example pages
https://store.steampowered.com/category/rpg/
https://store.steampowered.com/genre/Early%20Access/
https://store.steampowered.com/tags/en/Adventure/
https://store.steampowered.com/specials/

**Comment by alike03** [comment]
Thanks for gathering the links. I will look into it

**Comment by alike03** [comment]
With 47db99b71021179a0017540f9722509c6fc92c8a added a way to detect every untracked page. It solves mentioned pages.
