### ISSUE TITLE
Some games that are soon leaving are showing a date in the past

### ISSUE THREAD

**Issue by PhilippLoewen** [alike03/SubscriptionInfo#27]
Some games that are soon leaving a subscription service have a date in the past. 
![image](https://github.com/alike03/SubscriptionInfo/assets/6199606/d3c14713-f206-4bcb-a9db-027921887b0f)

I suspect this is because these games have been on game pass before and are now leaving for the second time.

I'm using Firefox 113.0.1 (64-bit) and alike03's Subscription Info on Steam v1.2.2.3

**Comment by alike03** [comment]
Only Game Pass has data for leaving games. But no information about the date. Only that they are soon leaving. The date you are seeing is the entry date (blue background). If there is a leave date. That is displayed with a red background.

**Comment by alike03** [comment]
No problem. Thanks for caring enough to leave an issue
