### ISSUE TITLE
Steam Deck is on PC Game Pass?

### ISSUE THREAD

**Issue by Vivelin** [alike03/SubscriptionInfo#28]
On the Steam Store front, I see an "ON PC GAME PASS" banner appear over the "Steam Deck, Gets Yours Now" thing in the top left and I can't imagine that's correct.

![image](https://github.com/alike03/SubscriptionInfo/assets/1766841/5debd314-0aa1-4aea-a5ed-bc185b16ee00)

**Comment by alike03** [comment]
Thanks. Happens when a game in "Recently Viewed" is on any Subscription service.
