### ISSUE TITLE
Incorrect Data/Listing - They Are Billions is NOT on EA PLAY PRO

### ISSUE THREAD

**Issue by C-BoT-AU** [alike03/SubscriptionInfo#29]
Unsure where best to log this so came here. Suspect it's just an old database entry that didn't get updated somewhere.
 
Game 'They Are Billions' | Steam App ID: 644930 | https://store.steampowered.com/app/644930/They_Are_Billions/

Shows incorrectly as available on EA Play Pro.
![image](https://github.com/alike03/SubscriptionInfo/assets/109268182/ebf580fd-b51a-4372-affe-c45a7ea6245c)

Hyperlink is to https://www.origin.com/store/they-are-billions/they-are-billions which redirects to https://www.ea.com/games/they-are-billions/they-are-billions but is 404:
![image](https://github.com/alike03/SubscriptionInfo/assets/109268182/8ec79520-4b96-4ebb-9b5a-8f656e995399)

Searching within the EA App also has no result:
![image](https://github.com/alike03/SubscriptionInfo/assets/109268182/1412d7df-6ae5-475e-bc27-53d1be93b4aa)

Side note - LOVE this extension! Makes choosing what to play next so much easier!

**Comment by alike03** [comment]
You miss typed the title of the game. It is showing up. EA only has the license for Play Pro. Not for selling. That's why it's not showing up in the shop.

![image](https://github.com/alike03/SubscriptionInfo/assets/8145921/5a5f791c-e27e-4260-9516-8e6f9a500f0b)
