### ISSUE TITLE
Incorrect database link between Doom 2016 (Steam) and Doom II Classic (Game Pass PC)

### ISSUE THREAD

**Issue by philcsf** [alike03/SubscriptionInfo#3]
Wrong game linked in the database, this game is not available on Game Pass PC - https://store.steampowered.com/app/379720/DOOM/

![image](https://user-images.githubusercontent.com/71151161/113721547-894bf380-96e7-11eb-8815-125e4d10d869.png)

**Comment by alike03** [comment]
Thanks for the info. 
Fixed the Steam ID of Doom 2 Classic.
