### ISSUE TITLE
Support GeForce Now

### ISSUE THREAD

**Issue by Victor239** [alike03/SubscriptionInfo#4]
Would be helpful to see it, their games list is available [here](https://www.nvidia.com/en-gb/geforce-now/games/).

**Comment by alike03** [comment]
Thanks, but for now no plans for that. I want to keep this addon strictly for Subscriptions Services. 
A game being on GeForce Now doesn't mean you don't have to buy it, which is the point why I created this.

There are also a couple of other reasons for not including it;
1 - I don't want this project to blow out of proportion, making it harder to maintain.
2 - It wouldn't work with the current text snippets.
3 - And currently there is enough areas that need some rework.
