### ISSUE TITLE
Epic Free Games

### ISSUE THREAD

**Issue by siddhantvirmani** [alike03/SubscriptionInfo#5]
Great extension - do you think it would be possible to include games given out for free from Epic? Here's a list: https://www.fanbyte.com/trending/epic-games-store-free-games-list/. I'd be happy to help - let me know. :)

**Comment by alike03** [comment]
Thanks. For now no plans for that. I want to keep this addon strictly for Subscriptions Services.

There are a couple of reasons for that. 
1 - I don't want this project to blow out of proportion, making it harder to maintain.
2 - It wouldn't work with the current text snippets.
3 -  And currently there is enough areas that need some rework.
