### ISSUE TITLE
Torchlight II not on gamepass but shows as if it was

### ISSUE THREAD

**Issue by Gizmo-of-Arabia** [alike03/SubscriptionInfo#9]
https://imgur.com/a/17sviGA

Torchlight II shows up as "on game pass" but I don't see it on game pass, only Torchlight III is there.

**Comment by alike03** [comment]
Tourchlight II is with EA Play included in Game Pass. You can access it trough EA Desktop.

![image](https://user-images.githubusercontent.com/8145921/132098800-9174dd07-0150-474f-9b48-4586c17d1358.png)
